# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\rhospital.auth\"L\n\x0b\x41uthRequest\x12\x11\n\tjwt_token\x18\x01 \x01(\t\x12\x17\n\x0frequested_scope\x18\x02 \x01(\t\x12\x11\n\ttarget_id\x18\x03 \x01(\t\"$\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x01 \x01(\t2V\n\x0b\x41uthService\x12G\n\x0cVerifyAccess\x12\x1a.hospital.auth.AuthRequest\x1a\x1b.hospital.auth.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=29
  _globals['_AUTHREQUEST']._serialized_end=105
  _globals['_AUTHRESPONSE']._serialized_start=107
  _globals['_AUTHRESPONSE']._serialized_end=143
  _globals['_AUTHSERVICE']._serialized_start=145
  _globals['_AUTHSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
