# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patient.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'patient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpatient.proto\x12\x10hospital.patient\"@\n\x14SinglePatientRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x02 \x01(\t\"Q\n\rCohortRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63ondition_code\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x03 \x01(\t\"0\n\x13PatientDataResponse\x12\x19\n\x11raw_database_json\x18\x01 \x01(\t2\xd9\x01\n\x12PatientDataService\x12\x65\n\x14GetSinglePatientData\x12&.hospital.patient.SinglePatientRequest\x1a%.hospital.patient.PatientDataResponse\x12\\\n\x10StreamCohortData\x12\x1f.hospital.patient.CohortRequest\x1a%.hospital.patient.PatientDataResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SINGLEPATIENTREQUEST']._serialized_start=35
  _globals['_SINGLEPATIENTREQUEST']._serialized_end=99
  _globals['_COHORTREQUEST']._serialized_start=101
  _globals['_COHORTREQUEST']._serialized_end=182
  _globals['_PATIENTDATARESPONSE']._serialized_start=184
  _globals['_PATIENTDATARESPONSE']._serialized_end=232
  _globals['_PATIENTDATASERVICE']._serialized_start=235
  _globals['_PATIENTDATASERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
