# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hospital_pb2 as hospital__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hospital_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """1. SERVIÇO DE AUTORIZAÇÃO 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyAccess = channel.unary_unary(
                '/hospital.AuthService/VerifyAccess',
                request_serializer=hospital__pb2.AuthRequest.SerializeToString,
                response_deserializer=hospital__pb2.AuthResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """1. SERVIÇO DE AUTORIZAÇÃO 

    """

    def VerifyAccess(self, request, context):
        """valida o JWT e retorna o nível de acesso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAccess,
                    request_deserializer=hospital__pb2.AuthRequest.FromString,
                    response_serializer=hospital__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """1. SERVIÇO DE AUTORIZAÇÃO 

    """

    @staticmethod
    def VerifyAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.AuthService/VerifyAccess',
            hospital__pb2.AuthRequest.SerializeToString,
            hospital__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PatientDataServiceStub:
    """2. SERVIÇO DE DADOS DE PACIENTES

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSinglePatientData = channel.unary_unary(
                '/hospital.PatientDataService/GetSinglePatientData',
                request_serializer=hospital__pb2.SinglePatientRequest.SerializeToString,
                response_deserializer=hospital__pb2.PatientDataResponse.FromString,
                _registered_method=True)
        self.StreamCohortData = channel.unary_stream(
                '/hospital.PatientDataService/StreamCohortData',
                request_serializer=hospital__pb2.CohortRequest.SerializeToString,
                response_deserializer=hospital__pb2.PatientDataResponse.FromString,
                _registered_method=True)


class PatientDataServiceServicer:
    """2. SERVIÇO DE DADOS DE PACIENTES

    """

    def GetSinglePatientData(self, request, context):
        """chamada unaria: Para buscar um paciente específico (Médicos/Estagiários)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCohortData(self, request, context):
        """server streaming: para pesquisadores buscar coortes gigantes sem estourar a memória
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSinglePatientData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSinglePatientData,
                    request_deserializer=hospital__pb2.SinglePatientRequest.FromString,
                    response_serializer=hospital__pb2.PatientDataResponse.SerializeToString,
            ),
            'StreamCohortData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCohortData,
                    request_deserializer=hospital__pb2.CohortRequest.FromString,
                    response_serializer=hospital__pb2.PatientDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.PatientDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.PatientDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientDataService:
    """2. SERVIÇO DE DADOS DE PACIENTES

    """

    @staticmethod
    def GetSinglePatientData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.PatientDataService/GetSinglePatientData',
            hospital__pb2.SinglePatientRequest.SerializeToString,
            hospital__pb2.PatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCohortData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hospital.PatientDataService/StreamCohortData',
            hospital__pb2.CohortRequest.SerializeToString,
            hospital__pb2.PatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataTransformServiceStub:
    """3. SERVIÇO DE TRANSFORMAÇÃO DE DADOS 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransformToFHIR = channel.unary_unary(
                '/hospital.DataTransformService/TransformToFHIR',
                request_serializer=hospital__pb2.TransformRequest.SerializeToString,
                response_deserializer=hospital__pb2.TransformResponse.FromString,
                _registered_method=True)


class DataTransformServiceServicer:
    """3. SERVIÇO DE TRANSFORMAÇÃO DE DADOS 

    """

    def TransformToFHIR(self, request, context):
        """recebe os dados brutos, anonimiza e converte para HL7/FHIR
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransformToFHIR': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformToFHIR,
                    request_deserializer=hospital__pb2.TransformRequest.FromString,
                    response_serializer=hospital__pb2.TransformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.DataTransformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.DataTransformService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataTransformService:
    """3. SERVIÇO DE TRANSFORMAÇÃO DE DADOS 

    """

    @staticmethod
    def TransformToFHIR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.DataTransformService/TransformToFHIR',
            hospital__pb2.TransformRequest.SerializeToString,
            hospital__pb2.TransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
