# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hospital.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'hospital.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehospital.proto\x12\x08hospital\"L\n\x0b\x41uthRequest\x12\x11\n\tjwt_token\x18\x01 \x01(\t\x12\x17\n\x0frequested_scope\x18\x02 \x01(\t\x12\x11\n\ttarget_id\x18\x03 \x01(\t\"$\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x01 \x01(\t\"@\n\x14SinglePatientRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x02 \x01(\t\"Q\n\rCohortRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63ondition_code\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x03 \x01(\t\"+\n\x13PatientDataResponse\x12\x14\n\x0craw_database\x18\x01 \x01(\t\">\n\x10TransformRequest\x12\x14\n\x0craw_database\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x02 \x01(\t\")\n\x11TransformResponse\x12\x14\n\x0c\x66hir_payload\x18\x01 \x01(\t2L\n\x0b\x41uthService\x12=\n\x0cVerifyAccess\x12\x15.hospital.AuthRequest\x1a\x16.hospital.AuthResponse2\xb9\x01\n\x12PatientDataService\x12U\n\x14GetSinglePatientData\x12\x1e.hospital.SinglePatientRequest\x1a\x1d.hospital.PatientDataResponse\x12L\n\x10StreamCohortData\x12\x17.hospital.CohortRequest\x1a\x1d.hospital.PatientDataResponse0\x01\x32\x62\n\x14\x44\x61taTransformService\x12J\n\x0fTransformToFHIR\x12\x1a.hospital.TransformRequest\x1a\x1b.hospital.TransformResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hospital_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=28
  _globals['_AUTHREQUEST']._serialized_end=104
  _globals['_AUTHRESPONSE']._serialized_start=106
  _globals['_AUTHRESPONSE']._serialized_end=142
  _globals['_SINGLEPATIENTREQUEST']._serialized_start=144
  _globals['_SINGLEPATIENTREQUEST']._serialized_end=208
  _globals['_COHORTREQUEST']._serialized_start=210
  _globals['_COHORTREQUEST']._serialized_end=291
  _globals['_PATIENTDATARESPONSE']._serialized_start=293
  _globals['_PATIENTDATARESPONSE']._serialized_end=336
  _globals['_TRANSFORMREQUEST']._serialized_start=338
  _globals['_TRANSFORMREQUEST']._serialized_end=400
  _globals['_TRANSFORMRESPONSE']._serialized_start=402
  _globals['_TRANSFORMRESPONSE']._serialized_end=443
  _globals['_AUTHSERVICE']._serialized_start=445
  _globals['_AUTHSERVICE']._serialized_end=521
  _globals['_PATIENTDATASERVICE']._serialized_start=524
  _globals['_PATIENTDATASERVICE']._serialized_end=709
  _globals['_DATATRANSFORMSERVICE']._serialized_start=711
  _globals['_DATATRANSFORMSERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
