# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import patient_pb2 as patient__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientDataServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSinglePatientData = channel.unary_unary(
                '/hospital.patient.PatientDataService/GetSinglePatientData',
                request_serializer=patient__pb2.SinglePatientRequest.SerializeToString,
                response_deserializer=patient__pb2.PatientDataResponse.FromString,
                _registered_method=True)
        self.StreamCohortData = channel.unary_stream(
                '/hospital.patient.PatientDataService/StreamCohortData',
                request_serializer=patient__pb2.CohortRequest.SerializeToString,
                response_deserializer=patient__pb2.PatientDataResponse.FromString,
                _registered_method=True)


class PatientDataServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSinglePatientData(self, request, context):
        """Chamada Unaria: buscar um paciente específico
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCohortData(self, request, context):
        """Server Streaming: Para buscar coortes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSinglePatientData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSinglePatientData,
                    request_deserializer=patient__pb2.SinglePatientRequest.FromString,
                    response_serializer=patient__pb2.PatientDataResponse.SerializeToString,
            ),
            'StreamCohortData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCohortData,
                    request_deserializer=patient__pb2.CohortRequest.FromString,
                    response_serializer=patient__pb2.PatientDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.patient.PatientDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.patient.PatientDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientDataService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSinglePatientData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.patient.PatientDataService/GetSinglePatientData',
            patient__pb2.SinglePatientRequest.SerializeToString,
            patient__pb2.PatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCohortData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hospital.patient.PatientDataService/StreamCohortData',
            patient__pb2.CohortRequest.SerializeToString,
            patient__pb2.PatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
