# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transform.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'transform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransform.proto\x12\x12hospital.transform\"C\n\x10TransformRequest\x12\x19\n\x11raw_database_json\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x02 \x01(\t\".\n\x11TransformResponse\x12\x19\n\x11\x66hir_json_payload\x18\x01 \x01(\t2v\n\x14\x44\x61taTransformService\x12^\n\x0fTransformToFHIR\x12$.hospital.transform.TransformRequest\x1a%.hospital.transform.TransformResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFORMREQUEST']._serialized_start=39
  _globals['_TRANSFORMREQUEST']._serialized_end=106
  _globals['_TRANSFORMRESPONSE']._serialized_start=108
  _globals['_TRANSFORMRESPONSE']._serialized_end=154
  _globals['_DATATRANSFORMSERVICE']._serialized_start=156
  _globals['_DATATRANSFORMSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
